# Generated by Django 6.0.1 on 2026-02-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_order_completed_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'În așteptare'), ('CONFIRMED', 'Confirmată'), ('SHIPPED', 'Expediată'), ('DELIVERED', 'Livrată'), ('CANCELLED', 'Anulată')], default='PENDING', max_length=10),
        ),
    ]
