# Generated by Django 6.0.1 on 2026-03-02 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0014_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('WISHLIST_EXPIRING', 'Wishlist Expiring'), ('PRODUCT_BACK_IN_STOCK', 'Product Back In Stock')], max_length=50)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order')),
                ('related_product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_confirmed', models.BooleanField(default=True)),
                ('order_shipped', models.BooleanField(default=True)),
                ('order_delivered', models.BooleanField(default=True)),
                ('wishlist_expiring', models.BooleanField(default=True)),
                ('wishlist_expiring_hours', models.IntegerField(default=6)),
                ('product_back_in_stock', models.BooleanField(default=True)),
                ('send_mail', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
