# Generated by Django 6.0.1 on 2026-03-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='related_order_id',
            new_name='related_order',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='related_product_id',
            new_name='related_product',
        ),
    ]
