# Generated by Django 6.0.1 on 2026-03-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_related_order_id_notification_related_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotificationsettings',
            old_name='wishlist_expiring',
            new_name='wishlist_expiring_soon',
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='new_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='order_cancelled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='wishlist_low_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('WISHLIST_LOW_STOCK', 'Wishlist Low Stock'), ('WISHLIST_EXPIRING', 'Wishlist Expiring'), ('PRODUCT_BACK_IN_STOCK', 'Product Back In Stock'), ('NEW_ORDER', 'New Order'), ('ORDER_CANCELLED', 'Order Cancelled')], max_length=50),
        ),
    ]
